#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=automaton2000
PIDFILE=/var/run/automaton2000/lock.pid
#ARGS=

#[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON

if [[ -r "$PIDFILE" ]]; then
	PID=$(cat "$PIDFILE")
fi

case "$1" in
 start)
   stat_busy "Starting $DAEMON"
   [[ -z "$PID" ]] && /home/chris/dev/automaton2000/src/automaton2000.py &>/dev/null
   if [[ "$?" == "0" ]]; then
     add_daemon $DAEMON
     stat_done
   else
     stat_fail
		 echo "Return code: $?"
     exit 1
   fi
   ;;
 stop)
   stat_busy "Stopping $DAEMON"
   [[ ! -z "$PID" ]] && kill $PID &>/dev/null
   if [[ "$?" == "0" ]]; then
     rm_daemon $DAEMON
     stat_done
   else
     stat_fail
		 echo "Return code: $?"
     exit 1
   fi
   ;;
 restart)
	 $0 stop
	 sleep 1
	 $0 start
	 ;;
 reload)
	 kill -SIGUSR1 $PID
   ;;
 *)
   echo "usage: $0 {start|stop|restart|reload}"
esac
